# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

source("header.R")

StrataL <- c('GBPUr','GBPUr_NonHab')
num<-length(StrataL)

#Read in data from excel generated by 04_output_Raw.R
UnreportLR<-list()
for (i in 1:num) {
  StratName<-StrataL[i]
  # Read in strata sheet and modify so GBPUs consistent with current 55 GBPUs
  # North Purcells = North Purcells + Spillamacheen
  # Central-South Purcells = South Purcells + Central Purcells
  # Drop those records since new has recalculated values based on 55
  UnrepLR <-
    read_xls(file.path(dataOutDir,paste('GBUnReported.xls',sep='')), sheet=StratName) %>%
    filter(!GBPU %in% c('Spillamacheen','South Purcells','Central Purcells'))

# Use the Flathead as the benchmark since there is data for that unit
# Based on McLellan et al. 2018 use a 1:1 reported to unreproted mortality
# Evaluate hunter density and inverse road density - ie higher unreported if more hunters and area is remote
# Normalize the other GBPUs to the benchmark
# Look at relationship between road density and hunter density
x=UnrepLR$RoadDensity
y=UnrepLR$HunterDensity
cor(x,y)
scatter.smooth(x=x, y=y, main="Road Density - Hunter Density", sub=paste('Correlation=',round(cor(x,y),2)))
linearMod <- lm(x ~ y)  # build linear regression model on full data
print(linearMod)

# Normalize road denisty, hunter density, and GBDensity
UnrepLR$norm_hunterD <- round(UnrepLR$HunterDensity/max(UnrepLR$HunterDensity,na.rm=TRUE),2)
UnrepLR$norm_GBD <- round(UnrepLR$GBDensity/max(UnrepLR$GBDensity,na.rm=TRUE),2)
UnrepLR$norm_roadD <- round(UnrepLR$RoadDensity/max(UnrepLR$RoadDensity,na.rm=TRUE),2)

# transform 'GB Density' to weibull for a better fit - see below
#fit.weibull <- fitdist(UnrepLR$norm_GBD, "weibull")
#UnrepLR$norm_GBD<-pweibull( UnrepLR$norm_GBD, fit.weibull[1]$estimate['shape'], scale=fit.weibull[1]$estimate['scale'] )

# Select Flathead as benchmark - report was done on MU 4-01 and Flathead has MU 4-02 as well, but
# conditions fairly uniform over GBPU so using entire GBPU should be a good approximation
bench_hunterD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_hunterD
bench_GBD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_GBD
bench_roadD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_roadD

# Combine scores GBPUs by those with highest hunters and highest road density - indexed to Flathead
UnrepLR$UnReportWbench<-round(((UnrepLR$norm_hunterD/bench_hunterD +
                                UnrepLR$norm_roadD/bench_roadD) *
                                UnrepLR$norm_GBD/bench_GBD/2*7.5),2)

UnRep<-data.frame(GBPU=UnrepLR$GBPU,
                  RoadDensity=UnrepLR$RoadDensity,RoadDNormal=UnrepLR$norm_roadD,
                  GBDensity=UnrepLR$GBDensity,GBDNormal=UnrepLR$norm_GBD,
                  HunterDensity=UnrepLR$HunterDensity,HunterDNormal=UnrepLR$norm_hunterD,
                  UnReport=UnrepLR$UnReportWbench)

UnreportLR[[i]]<-UnRep
}

WriteXLS(UnreportLR, file.path(dataOutDir,paste('UnReported_GBPU.xls',sep='')),SheetNames=StrataL)

#Make a pretty table for GBPU
df<-UnreportLR[[1]] %>%
  dplyr::select(GBPU,GBDensity,RoadDensity,HunterDensity,UnReport)
colnames(df)<-c('GBPU','GB Density','Road Density','Hunter Density','Unreported Ratio')

library("htmltools")
library("webshot")

export_formattable <- function(f, file, width = "100%", height = NULL,
                               background = "white", delay = 0.2)
{
  w <- as.htmlwidget(f, width = width, height = height)
  path <- html_print(w, background = background, viewer = NULL)
  url <- paste0("file:///", gsub("\\\\", "/", normalizePath(path)))
  webshot(url,
          file = file,
          selector = ".formattable_widget",
          delay = delay)
}
#(source: https://github.com/renkun-ken/formattable/issues/26)

DT<-formattable(df[order(df$GBPU),], list(
  GBPU = color_tile("white", "orange"),
  formattable::area(col = c('Road Density')) ~ normalize_bar("pink", 0.06),
  formattable::area(col = c('Hunter Density')) ~ normalize_bar("lightblue", 0.1),
  formattable::area(col = c('GB Density')) ~ normalize_bar("lightgreen", 0.1),
  'Unreported Ratio' = formatter("span", style = x ~
   ifelse(x < 2 ,style(color = "green", font.weight = "bold"), style(color = "red",
  font.weight = "bold")))
))

#webshot::install_phantomjs()
export_formattable(DT,file.path(figsOutDir,"GBUNreportedTable.png"))

FT <- formattable(DT, list(
  Name=formatter("span",
                 style = x ~ ifelse(x == "Technology", style(font.weight = "bold"), NA)),
  Value = color_tile("white", "orange"),
  Change = formatter("span",
                     style = x ~ style(color = ifelse(x < 0 , "red", "green")),
                     x ~ icontext(ifelse(x < 0, "arrow-down", "arrow-up"), x))) )

