# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

source("header.R")

StrataL <- c('GBPUr','GBPUr_NonHab','GBPUr_BEI_1_2','GBPUr_BEI_1_5')
num<-length(StrataL)

#Read in data from excel generated by 04_output_Raw.R
UnreportLR<-list()
for (i in 1:num) {
  StratName<-StrataL[i]
  UnreportLR[[StratName]]<-read_xls(file.path(dataOutDir,paste('GBUnreported.xls',sep='')), sheet=StratName)
}

#Use the GBPU strata that has non habitat removed
test<-UnreportLR[['GBPUr_NonHab']]

# On inspection looks like the Flathead is being used as a benchmark
Bench_pcHab_gt5000<-test[which(test$GBPU=='Flathead'),]$pcHab_gt5000_win50km2004
Bench_pcHab_gt0<-test[which(test$GBPU=='Flathead'),]$pcHab_gt0_kmperkm2
Bench_HunterDensity2004<-test[which(test$GBPU=='Flathead'),]$HunterDensity2004

# Create a new variable to check if benchmark theory is correct
test$Check_porp_pcHab_gt5000<-round(test$pcHab_gt5000_win50km2004/Bench_pcHab_gt5000,1)
test$Check_porp_Bench_pcHab_gt0<-round(test$pcHab_gt0_kmperkm2/Bench_pcHab_gt0,1)
test$Check_porp_HunterDensity2004<-round(test$HunterDensity2004/Bench_HunterDensity2004,1)

# Create some data.frames to inspect - yes the Flathead was the benchmark
Check_pcHab_gt5000_win50km2004<-data.frame(test$GBPU,test$pcHab_gt5000_win50km2004,test$pcHab_gt5000_PropBench,test$Check_porp_pcHab_gt5000)
Check_pcHab_pcHab_gt0_kmperkm2<-data.frame(test$GBPU,test$pcHab_gt0_kmperkm2,test$pcHab_gt0_PropBenchmark,test$Check_porp_Bench_pcHab_gt0)
Check_HunterDensity2004<-data.frame(test$GBPU,test$HunterDensity2004,test$HuntDens_PorpBenchmark,test$Check_porp_HunterDensity2004)

# Re-estimate unreported using same logic - Flathead is a benchmark - previously summed 4 values/2 for an
# unreported estimate of 2% in the Flathead - all others were standardized to that rating.
Bench_UnSecureHabitat<-test[which(test$GBPU=='Flathead'),]$UnSecureHabitat
Bench_FrontCountry<-test[which(test$GBPU=='Flathead'),]$FrontCountry
Bench_HunterDensity<-test[which(test$GBPU=='Flathead'),]$HunterDensity

test$Porp_UnSecureHabitat<-round(test$UnSecureHabitat/Bench_UnSecureHabitat,1)
test$Porp_FrontCountry<-round(test$FrontCountry/Bench_FrontCountry,1)
test$Porp_HunterDensity<-round(test$HunterDensity/Bench_HunterDensity,1)

test$UnreportedMort_unbound<-round(((test$Porp_UnSecureHabitat + test$Porp_FrontCountry + test$Porp_HunterDensity)/3)*2,1)
# Include Large Ungulate as a test - start to get better correlation between past metric and current
#test$UnreportedMort_unbound<-round(((test$Porp_UnSecureHabitat + test$Porp_FrontCountry + test$Porp_HunterDensity+ test$UngDen_PropBenchmark)/4)*2,1)
Check<-data.frame(test$GBPU,test$UnreportedMort_unbound,test$UnreportedMort_unbound2004,test$Porp_UnSecureHabitat,test$Porp_FrontCountry,test$Porp_HunterDensity)
View(Check)


TestData<-subset(test, AreaHa>0)
TestData[is.na(TestData)] <- 0

x=TestData$UnreportedMort_unbound
y=TestData$UnreportedMort_unbound2004

x=TestData$HuntDens_PorpBenchmark
y=TestData$Porp_HunterDensity

x=TestData$pcHab_gt5000_PropBench
y=TestData$UnSecureHabitat

x=TestData$pcHab_gt0_PropBenchmark
y=TestData$Porp_FrontCountry

x=TestData$UngHarvDensity_Ungperyearper1000km2_2004
y=TestData$HunterDensity2004


#pdf(file.path(dataOutDir,"GBMortPlots.pdf"))

cor(x,y)

scatter.smooth(x=x, y=y, main="2019 - 2004", sub=paste('Correlation=',round(cor(x,y),2)))
linearMod <- lm(x ~ y)  # build linear regression model on full data
print(linearMod)

#dev.off()

#Evaluate using only hunter density and backcountry - areas with high hunters and more backcountry have higher rates?
# Benchmark against the Flathead? where

