# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

source("header.R")

StrataL <- c('GBPUr','GBPUr_NonHab','GBPUr_BEI_1_2','GBPUr_BEI_1_5')
num<-length(StrataL)

#Read in data from excel generated by 04_output_Raw.R
UnreportLR<-list()
for (i in 1:num) {
  StratName<-StrataL[i]
  # Read in strata sheet and modify so GBPUs consistent with current 55 GBPUs
  # North Purcells = North Purcells + Spillamacheen
  # Central-South Purcells = South Purcells + Central Purcells
  # Drop those records since new has recalculated values based on 55
  UnrepLR <-
    read_xls(file.path(dataOutDir,paste('GBUnReported.xls',sep='')), sheet=StratName) %>%
    filter(!GBPU %in% c('Spillamacheen','South Purcells','Central Purcells'))

# Use the Flathead as the benchmark since there is data for that unit
# Based on McLellan et al. 2018 use a 1:1 reported to unreproted mortality
# Evaluate hunter density and inverse road density - ie higher unreported if more hunters and area is remote
# Normalize the other GBPUs to the benchmark
# Look at relationship between road density and hunter density
x=UnrepLR$RoadDensity
y=UnrepLR$HunterDensity
cor(x,y)
scatter.smooth(x=x, y=y, main="Road Density - Hunter Density", sub=paste('Correlation=',round(cor(x,y),2)))
linearMod <- lm(x ~ y)  # build linear regression model on full data
print(linearMod)

# Normalize road denisty and hunter density
UnrepLR$norm_hunterD <- round(UnrepLR$HunterDensity/max(UnrepLR$HunterDensity,na.rm=TRUE),2)
UnrepLR$norm_IroadD <- 1-round(UnrepLR$RoadDensity/max(UnrepLR$RoadDensity,na.rm=TRUE),2)
UnrepLR$norm_roadD <- round(UnrepLR$RoadDensity/max(UnrepLR$RoadDensity,na.rm=TRUE),2)

# Select Flathead as benchmark
bench_hunterD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_hunterD
bench_IroadD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_IroadD
bench_roadD<-UnrepLR[which(UnrepLR$GBPU=='Flathead'),]$norm_roadD

# Combine scores GBPUs by those with highest hunters and highest road density - indexed to Flathead
UnrepLR$UnReportWbench<-round(((UnrepLR$norm_hunterD/bench_hunterD + UnrepLR$norm_roadD/bench_roadD)/2),2)

# Combine scores GBPUs by those with highest hunters and lowest road density - indexed to Flathead
UnrepLR$UnReportWbencIrdh<-round(((UnrepLR$norm_hunterD/bench_hunterD + UnrepLR$norm_IroadD/bench_IroadD)/2),2)

# Combine scores GBPUs by those with highest hunters and lowest road density - raw
UnrepLR$UnReport<-round(((UnrepLR$norm_hunterD + UnrepLR$norm_IroadD)/2),2)

UnRep<-data.frame(GBPU=UnrepLR$GBPU,RoadDensity=UnrepLR$RoadDensity,RoadDNormal=UnrepLR$norm_roadD,InversRoadDNormal=UnrepLR$norm_IroadD,HunterDensity=UnrepLR$HunterDensity,HunterDNormal=UnrepLR$norm_hunterD,UnReportInvRd=UnrepLR$UnReportWbencIrdh,UnReport=UnrepLR$UnReportWbench)

UnreportLR[[i]]<-UnRep
}

WriteXLS(UnreportLR, file.path(dataOutDir,paste('UnReported.xls',sep='')),SheetNames=StrataL)


