# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

source("header.R")

StrataL <- c('GBPUr','GBPUr_NonHab','GBPUr_BEI_1_2','GBPUr_BEI_1_5')
num<-length(StrataL)

#Read in data from excel generated by 04_output_Raw.R
UnreportLR<-list()
for (i in 1:num) {
  StratName<-StrataL[i]
  UnreportLR[[StratName]]<-read_xls(file.path(dataOutDir,paste('GBUnreported.xls',sep='')), sheet=StratName)
}

test<-UnreportLR[[1]]

# Use the Flathead as the benchmark since there is data for that unit
# Based on McLellan et al. 2018 use a 1:1 reported to unreproted mortality
# Evaluate hunter density and inverse road density - ie higher unreported if more hunters and area is remote
# Normalize the other GBPUs to the benchmark
# Look at relationship between road density and hunter density
x=TestData$RoadDensity
y=TestData$HunterDensity
cor(x,y)
scatter.smooth(x=x, y=y, main="Road Density - Hunter Density", sub=paste('Correlation=',round(cor(x,y),2)))
linearMod <- lm(x ~ y)  # build linear regression model on full data
print(linearMod)

# Normalize road denisty and hunter density
test$norm_hunterD <- round(test$HunterDensity/max(test$HunterDensity,na.rm=TRUE),2)
test$norm_IroadD <- 1-round(test$RoadDensity/max(test$RoadDensity,na.rm=TRUE),2)
test$norm_roadD <- round(test$RoadDensity/max(test$RoadDensity,na.rm=TRUE),2)

# Select Flathead as benchmark
bench_hunterD<-test[which(test$GBPU=='Flathead'),]$norm_hunterD
bench_IroadD<-test[which(test$GBPU=='Flathead'),]$norm_IroadD
bench_roadD<-test[which(test$GBPU=='Flathead'),]$norm_roadD

# Combine scores GBPUs by those with highest hunters and highest road density - indexed to Flathead
test$UnReportWbench<-round(((test$norm_hunterD/bench_hunterD + test$norm_roadD/bench_roadD)/2),2)

# Combine scores GBPUs by those with highest hunters and lowest road density - indexed to Flathead
test$UnReportWbencIrdh<-round(((test$norm_hunterD/bench_hunterD + test$norm_IroadD/bench_IroadD)/2),2)

# Combine scores GBPUs by those with highest hunters and lowest road density - raw
test$UnReport<-round(((test$norm_hunterD + test$norm_IroadD)/2),2)

UnRep<-data.frame(GBPU=test$GBPU,RoadDensity=test$RoadDensity,RoadDNormal=test$norm_roadD,InversRoadDNormal=test$norm_IroadD,HunterDensity=test$HunterDensity,HunterDNormal=test$norm_hunterD,UnReportInvRd=test$UnReportWbencIrdh,UnReport=test$UnReportWbench)
View(UnRep)

WriteXLS(UnRep, file.path(dataOutDir,paste('UnReported.xlsx',sep='')))


