---
output:
  md_document:
    variant: markdown_github
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

<!-- Add a project state badge
See https://github.com/BCDevExchange/Our-Project-Docs/blob/master/discussion/projectstates.md
If you have bcgovr installed and you use RStudio, click the 'Insert BCDevex Badge' Addin. -->

# GB_Unreported
This repository contains [R](https://www.r-project.org/) code that summarizes spatial & tabular data to replicate the  Unreported mortality analysis done as part of the 2004 Grizzly Bear Harvest Management report - http://www.env.gov.bc.ca/wld/documents/gb_harvest_mgmt.pdf, to update that analysis with recent hunter day density, road denisty, core security area and front country metrics. Further, provided are some 

assess Hunter Day Densities by Wildlife Management Units (WMU). It generates a summary table by WMU and provincial rasters of Hunter Day Densities.

## Data
Updated hunter day density is from the GitHub repo: https://github.com/bcgov/HunterDensity
Additional input data is generated by the GB_Data GitHub repo:https://github.com/bcgov/GB_Data

Population and mortality data requires permission from FLNRORD Fish and Wildlife

### Usage

There are seven core scripts that are required for the analysis, they need to be run in order:

- 01_load.R
- 02_clean.R
- 03.1_analysis.R
- 03.2_analysis_integrate.R
- 04_output_Raw.R
- 04_output_Ratings.R
- 04_output_RevisedRatings.R


### Getting Help or Reporting an Issue

To report bugs/issues/feature requests, please file an [issue](https://github.com/bcgov/GB_Unreported/issues/).

### How to Contribute

If you would like to contribute, please see our [CONTRIBUTING](CONTRIBUTING.md) guidelines.

Please note that this project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.

### License

```
Copyright 2019 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
```

---
*This project was created using the [bcgovr](https://github.com/bcgov/bcgovr) package.* 

This repository is maintained by [ENVEcosystems](https://github.com/orgs/bcgov/teams/envecosystems/members).
